# --name vmCorey$(Build.BuildNumber)

trigger: none

pool:
  vmImage: 'VS2017-Win2016'

steps:
  - task: AzureCLI@2
    displayName: Azure CLI
    inputs:
      azureSubscription: amb
      scriptType: ps
      scriptLocation: inlineScript
      inlineScript: |
        az vm create --resource-group alan_bitterman --name vmCorey$(Build.BuildNumber) --image UbuntuLTS --admin-username corey  --generate-ssh-keys
